// hacer un pseudocodigo que nos indique el mayor de dos numeros

entero numero1, numero2

inicio

	escriba "Digite el primer numero "
	lea numero1
	escriba "Digite el segundo numero "
	lea numero2
	
	si numero1 > numero2 entonces
		escriba "El numero mayor es: ", numero1
	sino
		si numero2 > numero1 entonces
			escriba "El numero mayor es: ", numero2
		sino 
			escriba "Ambos numeros son iguales"
		fin si
	fin si
		
fin